# Site settings
title: Web Scratch
email: info@efcl.info
description: "ブラウザ/JavaScript等についてのブログ"
keywords:
  - "JavaScript"
  - "ブラウザ"
  - "ECMAScript"
  - "Objective-C"
  - "Firefox"
  - "拡張機能"
url: "https://efcl.info"
baseurl: ""
production_url : "https://efcl.info"
github_repo_url : https://github.com/efcl/efcl.github.io
icon: "/public/favicon.ico"
timezone: Asia/Tokyo
encoding: utf-8
include:
  - _headers
  - _redirects
exclude:
  - README.md
  - config.rb
  - about/node_modules
  - vendor
# Setup
author:
  name: 'azu'
  url:  https://efcl.info/
  twitter: azu_re
  github:  azu

paginate: 10
paginate_path: "page/:num"
permalink: /:year/:month/:day/:title/
# Github equal
safe: true
lsi: false
# Build settings
markdown: redcarpet
highlighter: rouge
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "with_toc_data"]
gems:
  - jekyll-sitemap
  - jemoji
